* [1] Chapter 1

Missed Opportunities and the Loss of Democracy

** 1.1 The Disfranchisement of Indian Tamils: 1948-49

Those who look at the political history of the Tamils since the 1930's
cannot help marvelling at the missed opportunities. The first of these
came and went before independence. The idea of a Ceylon Federation had
come as early as 1929 from S. W. R. D. Bandaranaike, who later became
Prime Minister of Ceylon. By this time portents of future communal
problems had already emerged. But no Tamil leader of importance fought
for a federal constitution at independence. The Tamil Congress under G.
G. Ponnampalam, which represented Tamil communal interests fought
instead for 50-50 representation in parliament, that is half the seats
for the minorities who then formed a little over 30% of the population,
the Tamils being about a quarter of the population. Perhaps, that was
the only way a Tamil politician with a communal electorate could hope to
become Prime Minister. Whereas a federal demand would have seemed a
reasonable guarantee of Tamil security, the 50-50 demand was seen to be
unreasonable to the Sinhalese, as it indeed was, and finally Ceylon
received independence on 4 February, 1948 without the Tamils having
either.

   Mr. Don Stephen Senanayake who was Prime Minister of the then
Dominion of Ceylon under the Soulbury constitution had secured the
co-operation of key sections of the Tamil leadership through personal
guarantees of good intent and the offer of ministries. The first
parliament had over 40% of the seats represented by candidates from the
minorities or left inclined candidates influenced by the minorities.
(The minorities consist of the Ceylon Tamils, Indian Tamils, Muslims and
Burghers.) But the Citizenship Act of December 1948 and the
Parliamentary Elections Amendment Act of 1949 put an end to that and
paved the way to reducing the representation in parliament of minorities
to less than 20%. What these Acts did was to make non-citizens of the
Tamil plantation labour who formed about 10% of the national population
or about a third of the minority population, and deprive them of their
vote. Besides having 7 parliamentary representatives, the Indian Tamil
vote influenced the decision in 20 other constituencies, generally to
the ruling U.N.P.'s disadvantage.

   What was surprising, however, was that almost all of the Tamil elite
representing the Ceylon Tamils through both Mr. Senanayake's United
National Party and the Tamil Congress, either voted for the bills or
were not serious about opposing them. Mr. G. G. Ponnampalam, the leader
of the Tamil Congress, opposed the first bill and voted for the second,
having become a member of the cabinet. This somersault on the
unprincipled calculation that, on the goodwill of the U.N.P. depended
their personal power and vested interests. The Sinhalese elite
discovered very early that they could easily call the bluff of the Tamil
elite, especially the Colombo Tamil.

   Kumari Jayewardene has pointed out in her writings (see Lanka
Guardian June/July 1984) that the vote in a parliament which
disenfranchised the Indian Tamils was not simply a communal vote.
Strenuous opposition to this bill came from the major left parties - the
Trotskyite L.S.S.P. led by Dr. N. M. Perera, the Bolshevik-Leninist
party led by Dr. Colvin R. De Silva, and the Communist party led by Mr.
Pieter Keuneman. Most M.P.'s from these parties were Sinhalese. A
prominent Buddhist and doctor, H. Sri Nissanka opposed this piece of
Legislation on the grounds that it ignored the first principle of law.
Other prominent Sinhalese Independents who voted against the bills were
Wilmot Perera, R. S. Pelpola, I. M. R. A. Iriyagolla and Lakshman
Rajapakse.

   It would be much nearer the truth to say that the vote was along
class lines. Again it is probably wrong to say that Mr. D. S. Senanayake
was involved in a deep anti-Tamil conspiracy to bring about Sinhalese
domination. Nor is it possible to make a case that Mr. Senanayake was
hatching a diabolical master plan to colonise Tamil areas with
Sinhalese. When work for the Gal Oya settlement scheme in the Eastern
province had been completed, first preference was given to people from
the province. It was only after about six months, when faced with the
paucity of local applicants, that the doors were opened to applicants
from other provinces. As regards the Citizenship Act of 1948 and its
sequel, what almost certainly motivated D. S. Senanayake was his alarm
over the strength in parliament of the working class based parties of
the Left, which comprised 20 out of a total of 95 seats in parliament.
Against this the U.N.P. obtained only 41 seats in the 1947 elections, 7
short of a simple majority. There was also a distinct possibility of a
coalition government of the Left sometime in the future. It was thus
natural for the U.N.P. to think of perpetuating its political and class
dominance by knocking out a large section of the working class which was
the most easily isolated. Subsequently in the 1952 elections the U.N.P.
increased its number of seats to 54. (See A. J. Wilson's "Electoral
Politics in an Emergent State", Cambridge University Press, 1975.)

   Thus the first and most grievous blow against democracy was struck by
the passage of these bills with Tamil connivance. In poignant words
during the course of the parliamentary debates, Dr. N. M. Perera, the
leader of the L.S.S.P. said: "I thought racialism of this type died with
Houston Chamberlain and Adolph Hitler. I do not believe that anyone
claiming to be a Statesman would ask us to accede to a bill of this
nature ... We cannot proceed as if we were God's chosen race quite apart
from the rest of the world; that we and we alone have the right to be
citizens of this country."

   S. J. V. Chelvanayakam, then a member of the Tamil Congress, strongly
dissented from these bills and left the T.C. to form a new party, the
Federal Party, which was 25 years later to absorb other Tamil parties
and become the Tamil United Liberation Front (T.U.L.F.). Dr. E. M. V.
Naganathan and Mr. C. Vanniasingham were two other eminent figures who
left the T.C. to form the Federal Party whose Tamil name read: "The
Tamil State Party." The latter was closely associated in the
negotiations which led to the Bandaranaike-Chelvanayakam pact of 1957,
the first attempt to find a political solution to the communal problem.
This was not implemented as a result of pressure from extremist
Sinhalese and Buddhist opinion. One of the major demonstrations against
this pact was the long march from Colombo to Kandy led by J. R.
Jayewardene who was trying to use the occasion to revive the fortunes of
the U.N.P., which had suffered a debacle in 1956.

   While the Left saw in the legislation of 1948/49 a crude expression
of class hatred overlaid by a veneer of racialism, Mr. Chelvanayakam
stressed the communal aspect of it in his contributions to the debates.
He pointed out that this set a very disturbing precedent for the
government to shut away the opinion of any section of the population it
did not like; that no one could therefore live comfortably with this
act; and that it may hit almost anyone some day. Mr. Chelvanayakam said
during the course of a speech: "This bill is a piece of legislation not
based on the highest principles on which differences and difficulties of
inter-communal problems have to be resolved and I oppose it firstly on
that ground." His fears were well founded. The sixth amendment to the
Republican constitution of 1978 passed in the middle of the July 1983
race riots unseated all the T.U.L.F. M.P.'s in parliament.

   One of democracy's main planks is the impartiality of the law and its
agencies for enforcement. When there is a situation in which one can go
through the prohibitively expensive process of the law and yet not find
justice, it becomes pregnant with violence and anarchy. Soon after the
1952 elections, the Federal Party concentrated its energies on fighting
three important and expensive legal battles. Two of these were election
petition cases. The most important of these legal battles was the
challenging of the Citizenship Act, No. 18 of 1949, and the
Parliamentary Elections Amendment act No. 48 of 1949.

   Section 29 of the Soulbury Constitution of 1948 provided that
Parliament could not enact legislation which 1. prohibits or restricts
the free exercise of any religion; 2. makes persons of any community or
religion liable to disabilities or restrictions to which persons of
other communities or religions are not made liable; 3. gives to persons
of any community or religion any privilege or advantage which is not
given to persons of other communities or religions; and 4. alters the
constitution of any religious body except with the consent of the
governing authority of that body. It was also provided that parliament
could not vary the provisions of the constitution in a manner which
infringed these.

   It seemed a clear cut case that the act in question was against the
spirit of the constitution. Apart from all legal niceties, the
legislation was immoral and went against the assurances of good intent
and good faith given by the Honourable Prime Minister in persuading
others to accept the Independence Constitution.

   In challenging the legislation it was argued that the acts
discriminated against the Indian community in contravention of section
29. The argument went that these acts disenfranchised Indians resident
in Ceylon who had earlier enjoyed the vote. Following the passing of the
legislation the vote was to be confined to citizens of Ceylon. The
Indian and Pakistani Residents (Citizenship) Act, No. 34, of 1949
permitted only those Indians and Pakistanis resident in Ceylon who
satisfied some stringent conditions to obtain Ceylonese Citizenship. It
was pointed out then that many prominent Ceylonese of the day, including
the Prime Minister, could not have satisfied these conditions -- for
they were born in times when there was much laxity in registering
births, leave alone those of their immediate forebears.

   It was true that there was a genuine human problem here. The Indian
plantation labour formed a very deprived class without means of social
advancement, kept isolated in line rooms, and alienated from the Kandyan
peasantry by the European plantation owners. Outsiders had to seek
permission to enter the estates. The formation of the estates too had
involved the takeover of some lands from the Kandyan peasantry. The
extent of this takeover was exaggerated by propagandists. Much of the
planting was done on land where thick jungle was cleared by Indian
coolie labour working in conditions of poor health and disease. At the
same time the Indian labour had been brought from the middle of the
nineteenth century, travelling in conditions resulting in a high death
rate in the early days, and many of them now knew of no other country
but Ceylon. In the nature of things Kandyan anger tended to be turned
against the Indian labour rather than against the European plantation
owners and the low country Sinhalese businessmen who made money in the
commerce of the hill-country. It is relevant here that during the
debates Mr. S. W. R. D. Bandaranaike, then Minister of Home Affairs, had
distanced himself from the U.N.P.'s position by saying that while he
supported the legislation in the interests of statesmanship and wisdom
and in the interests of peace, he would have preferred the problem to
have been approached from another angle. He said in his speech that
Prime Minister Nehru of India had already shown considerable
understanding towards the problem. Bandaranaike's approach involved
determining in the first instance the number of persons of Indian origin
who could be absorbed. Patience, consultation and a commitment to
justice could have yielded solutions which would have been acceptable to
both the plantation labour and the Kandyans. For instance the Federal
Party later suggested that the plantation labour could be encouraged to
resettle in the Tamil speaking Northern and Eastern provinces where
settlements were being opened up. It may be noted that during the State
Council era of the 1930's Dr. N. M. Perera pointed out the danger
arising from an influx of Indian labour. It was none other than D. S.
Senanayake who argued that it was very beneficial to the plantation
industry.

   The litigation first went in favour of the plaintiffs when at the
Kegalle District Court, the District Judge N. Sivagnanasundaram held the
legislation to be invalid on the grounds that the acts sought to deprive
the Indian community of the franchise. The Supreme Court in Mudanayake
vs. Sivagnanasundaram (53 N.L.R. 25, 1952) quashed the decision of the
District Court on the grounds that the acts were clear and unambiguous;
and that the acts in question applied to all communal groups in a like
manner and were thus not discriminatory. When appealed to, the Judicial
Committee of the Privy Council upheld the Supreme Court's verdict.

   Everyone - both sides to the dispute - knew that the series of
legislation represented a legal conjuring trick. Everyone knew that the
intended victims were the Indians. Racist sentiments expressed during
the course of the debate were proof of that. The sting of the
legislation was obscured by being distributed in three separate acts.
Each act taken by itself may seem fairly respectable. A judge may thus
hold them each to be valid without appearing to be too partial. By every
accepted universal norm, the legislation was unjust and discriminatory.
Many in this country agreed with that. Thus did Great Britain help to
strike the first blow against democracy in independent Ceylon. Many felt
at that time as later, that the quality of British justice meted out by
the Privy Council is not unaffected by Britain's other interests. The
tea plantations were largely British owned and Britain had a naval base
at Trincomalee.

   At that time opponents of the legislation were free to hold
demonstrations, protest rallies and satyagrahas in Colombo, which they
did. This freedom too was to be taken away. The process which started in
1948 (Kandasamy killing, 1952 rice hartal) culminated 30 years later
when strikers and protesters would be stabbed and attacked with bicycle
chains by hooligans in the pay of government ministers, while the police
stood by. The 1948/49 legislative enactments had set a precedent for the
politics of immoral manipulation rather than consultation. With
Jayewardene on top, people would watch incredulously the controversies
surrounding the appointments of Chief Justices. One of the judges
appointed by President Jayewardene to go into the abuses of power by
Mrs. Bandaranaike during her period as Prime Minister from 1970 to 1977
and who recommended a deprivation of her civic rights for 7 years, was
later found guilty of improper conduct during a previous posting. During
the months April/May 1971 and after the passage of emergency regulation
15A in July 1983, every armed uniformed person became a potential Judge
Jeffreys in his own right. The law courts became superfluous in a large
number of important instances, thus vitiating an important pillar of
democracy.

   It was then left to Jayewardene, who had in a base manner campaigned
against the Bandaranaike - Chelvanayakam pact of 1957, to accept under
duress, the political solution along the same lines contained in the
Indo-Lanka accord of 1987.

   There were other ironies too. During the course of the 1947/48
debates, Mr. A. Ratnayake accused Mr. S. Thondaman, the leader of the
Ceylon Indian Congress, of having a vision of Ceylon federated with
India. Mr. Thondaman would in time become a close ally of the U.N.P.
under Jayewardene, helping the latter to win both the presidential
elections and the controversial referendum in 1982. The latter, as will
be explained later, deprived the entire country of the right to elect
representatives for a crucial period of six years. Thus by slipping a
few dubious benefits to the plantation labour, Jayewardene was able to
secure peace in the plantations together with his unfettered
continuation in power. It was ironical that D. S. Senanayake had himself
advocated federation of Ceylon with India, of course protecting Ceylon's
interests.

   Some may feel that Mr. Ratnayake's fears of a Ceylon federated with
India came close to being realised with the signing of the Indo-Lanka
Accord of July 1987. But this had much more to do with the manner in
which Mr. Ratnayake voted on the bills in question, than with anything
Mr. Thondaman did in the intervening years.

** 1.2 The Left

The performance of the Left in the wake of the General Elections of 1947
had repercussions which strongly influenced the future. With several
opportunities before it the Left was hamstrung by differences which were
expressed in hyperbole and by an ambiguous attitude to the institution
of parliament. The Left opposition at that time was made up of the
L.S.S.P., the B.L.P. (Bolshevik Leninist Party) and the Communist Party.
They controlled between themselves 20 seats out of 95 for which
elections were held, with the U.N.P. controlling 41 and were thus placed
in a minority situation. Feverish attempts were made by independents and
groups opposed to the U.N.P. to form a united front and offer itself as
an alternative government. The grouping which formed the government
would have received a bonus of six parliamentary seats which were to be
appointed by the Governor General (the King's representative) on the
Prime Minister's recommendation. The L.S.S.P. declined to participate in
such a government. Its leader Dr. N. M. Perera explained that they were
a "revolutionary party" and would therefore not serve in a "capitalist
government". They were willing, however, to assist those who may take
office in an alternative progressive government. For nearly three years
thereafter the Left could not even agree to a Leader of the Opposition.
Dr. N. M. Perera was elected leader in June 1950. The communist party
argued that the idea of "His Majesty's Loyal Opposition" being part and
parcel of the government, implied an acceptance that the present social
order must continue.

   Having got into parliament, the Left had no clear idea of what it
wanted to do with it. In its rhetoric it did not seem to accept the
parliament as the arbiter of the nation's destinies. A mixture of both
fear and opportunism led the U.N.P. government to adopt an
uncompromising attitude to the Left. Instead of taking an enlightened
view and trying to persuade the Left that parliament was a place for
reason and contained the possibility of the realisation of its social
goals, it proceeded to disenfranchise a large section of the Left's
support base. Furthermore there was a reluctance to consult and do
business with the Left and the needs of the constituencies represented
by the Left were ignored. Describing the U.N.P.'s view of the
Opposition, Sir John Kotelewala said on 9 June 1950: "Our Opposition
today is an Opposition which does not believe in the democratic system.
That is why the government finds its task so difficult. We have to fight
the Opposition not as an Opposition but as enemies of the state... once
they got in they would not get out. There is no guarantee that you would
ever have a chance to go to the ballot again."

   The ambivalence of the Left to the institution of parliament was
expressed in a statement issued on the decision to boycott the ceremony
of 11 January 1949 in which the speaker's mace and chair were presented
by the British House of Commons to its progeny. Amongst the reasons
advanced was "the consistent failure of the government to consult the
Opposition on all such matters on which by parliamentary tradition, it
is the duty of the Government to consult the Opposition." This was a
complaint that it was not being treated as the King's loyal Opposition.
While the British educated learned men of the Left languished in
uncertainty, the business of the day was carried on by squires and
ex-military officers adept in the ways of the world.

   There were attempts from 1947 onwards to forge unity within the Left
and these met with limited success. The B.L.P. merged with the L.S.S.P.
on 3 June 1950. In early 1951 the L.S.S.P. affirmed that its ultimate
objective lay along that of "a direct mass struggle alone and not
through parliamentary devices and manoeuvres." (See A. J. Wilson,
"Oppositional Politics in Ceylon (1947-68)," Government and Opposition,
Vol. 4 No. 1 Winter 1969).

   The Left had thus adopted a course where its practice was different
from its rhetoric. Its ambiguities were fully exploited by its
opponents. Although the rhetoric of the Left was innocuous in comparison
with the racist rhetoric of the Right, the Right used it to raise the
bogey of an atheistic dictatorship. The Left leaders received their
education in Britain under men like Harold Laski at the London School of
Economics during the impressionable period following the Russian
revolution. When they spoke of "direct mass struggle" they adopted the
rhetoric and imagery of the Russian revolution to mean something vague
and undefined. They were by practice and conviction democrats for the
most part and certainly on record more so than the U.N.P.. There is no
reason why direct mass struggle cannot be democratic. Thus while the
Left talked in the imagery of war, the Right talked peace and practised
war - through both legislation and police action. The spectre of a
Marxist atheistic dictatorship was raised again, more strongly, in the
campaign preceding the 1970 elections. The Left's ambivalence in those
days prevented it from having a workable program to deliver its goods.
It had to keep its constituency of workers in the hope that its program
would somehow be realised. Its use of the strike weapon through unions
allied to the Left in a largely agrarian country tended to serve more
the propaganda of the Right.

   In many ways the fate of the parliamentary Left resembled that of the
T.U.L.F. in the 1970's and early 1980's. The Left had failed to resolve
its ambivalence towards parliament as an instrument of government. On
the one hand it had sought representation in parliament and wished to
participate fully in its business. Having come this far, it did
recognise in parliament a potential source of good. But then from the
outset it should have taken the opportunity to form an alternative
coalition government and use all available levers to implement a program
of reform. This it had declined to do out of deference to ideology and
preferred to hint at revolution from the sidelines. But the electorate
wanted reform that would improve its lot in terms of something tangible.
Moreover, the Left did not attempt to modify its approach in order to
appeal to the "middle level of Ceylonese opinion comprising the national
minded swabasha [2] ¹ -educated intelligentsia" who felt left out by the
U.N.P.. It was left to Mr. S. W. R. D. Bandaranaike's S.L.F.P. to fill
this vacuum.

   The increasing disparity between what it promised and what it
achieved finally led the Left to despair and made them secure
participation in coalition governments in the early sixties and in
1970-75 after making abject compromises on principles. When an actual
youth uprising came in 1971, the Left then in power, found itself on the
defensive, while an elite led army and police massacred 10 to 15
thousand Sinhalese youth particularly educated unemployed rural youth.
Moreover, Dr. Colvin R. de Silva presided over the drawing up of the
republican constitution of 1972 which did away with section 29 of the
Soulbury constitution which was nominally supposed to safeguard
minorities. It also enshrined Buddhism as the state religion and
Sinhalese as the sole official language, much against what the Left had
upheld quite valiantly in the 1950s. At the time the influence of the
Left had been such that during the race riots of 1958, it had been able
to mobilise its members in Colombo and protect the Tamils in some areas.
But when President Jayewardene extended the life of the parliament in
December 1982 by a fraudulent referendum, the Left could not even bring
out a demonstration.

   Though the Left may not have been very conscious of it, it had
largely replayed the tragedies of some of the European social democratic
parties in the decades leading up to the First World War (1914-18). The
Danish Social Democratic Party started with a trade union base, shunned
Marxist doctrines, steadily increased its strength by adapting its
programme to the needs of agricultural co-operatives and, in 35 years,
attained power in a coalition government by 1913. It thus attained a
position where it was able to implement social welfare legislation.
Socialist parties followed similar courses in Britain and Scandinavia.
The German Social Democratic party founded in 1875 and led by August
Bebel adopted the Gotha programme. This was a compromise programme which
contained the view of its northern faction led by Lassalle that
revolutionary Marxism had been rendered out of date by the existence of
universal suffrage; in other words that proletarian interests were
compatible with parliamentary democracy. It also accepted Marx's view of
the class struggle and his materialist interpretation of history. It
thus combined resolutely revolutionary pronouncements with an equally
determined reformist and revisionist policy. Formal unity was thus
preserved at the cost of alienating liberal and middle-class opinion and
perpetuating an unresolved contradiction between principle and practice.
It resulted in an ineffective combination of challenging absolutist
pronouncements and feeble action; for the party did not gain sufficient
strength. The party even developed a revisionist faction led by Edward
Bernstein who argued that Marxist analysis and predictions were not
borne out by events. For the workers were not getting remorselessly
poorer and more repressed - they were coming to be better off and freer.
Some members of this faction went on to drop the ideal of the
international brotherhood of workers and fell in with the rising tide of
militarism and nationalism in Germany which led to the World War of
1914-18.

   In Ceylon today a reconstituted Left which will recapture the lost
ideals of non-sectarian socialism and will communicate them to the
masses in simple terms that they could understand and agree with, is
still in its birth pangs. The Left recently lost two promising leaders
in Sarath Muttetuwegama and Vijaya Kumaranatunge.

** 1.3 The Tamils

From the 1940's the Tamil leadership had, as we have seen, largely shown
a preference for doing what appears clever in the interests of
preserving material gains rather than what is principled. This
predominance of manipulation over morality produced gains which were
only illusory. If Tamils did not show an interest in federalism before
independence, there were sound material reasons for this. Their middle
class depended on government jobs outside the Tamil speaking areas. A
unitary state is not a moral issue and in Ceylon such a state could have
been workable with adequate devolution such as in Britain. The peoples
of Ceylon after all have much more in common in terms of origin and
culture than do the people of Britain. Conflicts of the past too have
been dynastic rather than along lines of language or religion.

   Where the Tamil leadership went wrong is that, having failed to
obtain the unreasonable 50-50 representation, they agreed to
independence under a highly centralised constitution (unlike in Britain)
with its brand of communal politics. Having made this mistake, no
attempt was made to integrate into a national grouping that would
articulate Tamil interests. The pursuit of communal politics, the 50-50
demand, followed by the abject capitulation of most of the Ceylon Tamil
leadership in selling out the upcountry [3] ¹ Tamils in return for
ministerial positions and the assurance that Ceylon Tamils will not be
touched - all helped to create a stereotype image of the Ceylon Tamil as
an unprincipled person who can be bought over by promises of transient
material security. The failure of the Tamils to adopt a form of national
level politics, enabled Sinhalese racists to build up stereotype images
of Tamils and exploit them to foment racial hatred.

   On the other side many Tamils argue that communal politics was forced
on them. The F.P.'s attempts at finding legal remedies to the iniquitous
citizenship legislation were blocked, indicating that relief through
legal and constitutional means was not available to them. After 1960
when the Left adopted a communal line, it became far more difficult for
Tamils to enter politics at national level. It can also be pointed out
that it was the Tamil Opposition in parliament that helped to keep
democracy alive during some crucial periods.

   But even from the position of a regional party, the F.P. and the
T.U.L.F. could have actively supported national causes and won Sinhalese
confidence. This it was prevented from doing by its ideology that was
founded on the assumption of Sinhalese perfidy. The general strike of
1980 and the obnoxious manner in which the government handled it,
together with the fraudulent referendum of December, 1982 represented
burning national issues. But the Tamil leadership under the T.U.L.F.,
given their narrow nationalist ideology, were able to dismiss these as
problems of the South. Here again there was a preference, as in 1948/49,
for what may seem clever and opportune as against what was right and
fair by the whole country. The government of J. R. Jayewardene was able
to buy the silence of the T.U.L.F. on these important national issues by
a mixture of threat, vague promises and a few perks. This again helped
to isolate the Tamils and lay them at the mercy of Jayewardene's
government and its cynicism.

   The other matter is the T.U.L.F.'s ambivalence towards parliament
during the years 1977-83, to which it was led by a nationalist ideology.
Rhetorically it regarded the parliamentary vote it secured in the Tamil
areas as a mandate to form a separate state of Tamil Eelam and the
police and army in Tamil areas were regarded as occupying forces. It
further hinted at a secret plan to make the separate state a reality.
Thus in the public mind a certain legitimacy was given to the Tamil
youth militancy. But in its actions the T.U.L.F. behaved like a loyal
parliamentary opposition. As it turned out, this unresolved ambivalence
was a dangerous mix. While the T.U.L.F. hinted at war and practised
peace, it was left to others to practise war.

   After the 1977 elections, the T.U.L.F. and those who voted for them,
did want them to participate in the business of parliament. The
priority, as the Tamils saw it in the wake of the 1977 race riots, was
the resettlement of refugees and the economic development of the Tamil
areas in the North and East. Money was canvassed for this from
charitable organisations and from Tamils living abroad. Tamils were
encouraged to invest in their areas. These activities were going on and
services normally provided by the state, such as banking, transport,
communication and even police were utilised. Tamil farmers were
benefitting from loan and agricultural services provided for the whole
country. Given that the Tamils wanted these, the natural approach should
have been to recognise in the parliament a source of potential goodness
and press for reform of the existing state machinery so that it would be
fairer. Its political activity should have been directed at finding a
common cause with a country-wide opposition and to isolate the racist
elements. It was not only the Tamils who had problems with the police.
There were Sinhalese peasants in Moneragala and elsewhere whose lands
were being taken over for the benefit of multi-nationals. There was
rampant government corruption. Our forests were being denuded by
politicians who wanted a quick buck. But what the T.U.L.F. and the Tamil
leadership actually did was to keep silent when police and servicemen
carrying out ordinary civil functions were attacked. The moral dilemma
was dodged - can we pretend that we had no obligation to those whose
services we utilised because our ideology said that they were aliens? As
we shall see, the result was to awaken the worst instincts in a
government that was already bad enough.

   What the Tamil militant groups carried over from the Tamil
parliamentary leadership was the world view based on Sinhalese perfidy.
Everyone is conscious of past tactical errors of the Tamil leadership.
But we have not learnt from our experience and continue the same
blunders in different forms, principally because of a lack of moral
conviction. The desire for material security reflects itself today in
the form of seminars on development and a rejoicing over the departure
from the Eastern province of many terror stricken Sinhalese, oblivious
of the senseless assassinations and misery that have afflicted all
communities -- Sinhalese, Muslims and Tamils. The moral perversity
reflects itself in casual talk of horse deals -- one day with the
government against the IPKF, next with the IPKF against Sinhalese and so
on. In a bid to justify terrorist attacks on Sinhalese in the East, some
have suggested a parallel with the repatriation of Indian plantation
labour to India from the hill country; as if the Kandyan Sinhalese would
be justified in bombing and shooting Indian Tamils. It would be to
justify the terrible anti-Tamil violence of 1983 for which the Sinhalese
are still paying the price. With many members of the Tamil elite,
cleverness without a moral commitment is approaching a fever of
insanity. If our past should teach us anything, it should be to regain
the moral initiative, mend our relations with the Sinhalese, and pursue
our interests in a national context, with malice towards none.

   The foregoing has dwelt on missed opportunities in the 1940's, and
how the behaviour of the actors at the time set the pattern for years to
come, leading up to India's direct entry into the affairs of this
country. To throw further light on the current crisis the sketch that
follows focuses on two other missed opportunities: the referendum of
December 1982 and the two months following the July 1987 Indo-Lanka
Accord. The events that followed the first led to the July 1983 racial
riots. In both instances the Tamil disease that contributed to the
crises was the same, with some shift in the actors.[Top]



² Mother tongue

³ Ceylonism for hill-country

¹ Roofing material from coconut fronds

------------------------------------------------------------------------

